### ISSUE TITLE
Error no dataset configure for backup !!!

### ISSUE THREAD

**Issue by ghost** [adaugherity/zfs-backup#12]
hi .. im try a script for backup snapshot to another server using zfs. but i have error like this

No datasets configured for backup!  Please set the 'com.edu:backuptarget' property
appropriately on the datasets you wish to back up.

what the meaning "com.edu:backuptarget" ? 

if i see a command "zfs get datapool/fs1" 
im not see property "com.edu:backuptarget"

and if im add manual will be error no value property.

anyone can help ? or give me any reference ? 

thanks :)

**Comment by cpzengel** [comment]
you have to mark the datasets by setting a meta information

zfs get all shows all properties by zfs
zfs set mymeta:information have a ":" in it are user set properties

so use

zfs set com.edu:backuptarget=basename datapool/fs1

to trigger the script to replicate

chriz

**Comment by ghost** [comment]
thanks for reply ...

what i've missed .
i have error again 

Warning: data/fs1 has invalid backuptarget property 'backup' -- skipping.

i have zfs = data/fs1 for backup and im done set property edu.tamu:backuptarget=backup 

can u help me ???

**Comment by adaugherity** [comment]
Right, you need to set the property to either "fullpath" or "basename", as described in step 8 in the README.  "backup" is not a value it accepts.

**Comment by ghost** [comment]
im have error again like this 

Error fetching remote snapshot listing via ssh to root@zfs-backup

what i've missed again.. ? 

pleasee help

**Comment by white-rabbit07** [comment]
Hi. I used the command 
"zfs set zfs:backup=basename rpool/vm-600-disk-0" to mark a VM to be copied by your script.
How to unset this option or how to set it back to a default value so that the script won't use these snapshots any more??

**Comment by adaugherity** [comment]
Use `zfs inherit ...` to clear a property.  Quoth the [man page:](https://www.freebsd.org/cgi/man.cgi?query=zfs&manpath=FreeBSD+12.0-RELEASE+and+Ports)

> Use	the "zfs     inherit" command to clear a user property.	If the property	is not defined
     in	any parent dataset, it is removed entirely.
