### ISSUE TITLE
Handle special case root of the pool.

### ISSUE THREAD

**Issue by litwol** [adaugherity/zfs-backup#2]
Having the following pool layout:

tank
tank/a
tank/a/b
tank/c
...

all of the filesystems are handled well, due to -e/-d FS=${DATASET#*/} and FS_BASE=${DATASET##*/} 
However, this doesn't work for the very pool root (not sure what the official name for it is).

"tank" doesn't match neither FS nor FS_BASE and will result in the following remote layout:
remote/tank
remote/a
remote/a/b
remote/c
...

the goal is to make sure local "tank" (pool root) can sync into "remote" (remote pool root).

I used the following code to provide special case handling for pool root, right after -e/-d case handling (https://github.com/adaugherity/zfs-backup/blob/4eb8815ccfe3c833dbde73855265e19e2320fd11/zfs-backup.sh#L146) :

    # Special case for pool root
    if [[ "$DATASET" != */* ]]
    then
      TARGET="$REMPOOL"
    fi

please add this special case into your repo.

**Comment by adaugherity** [comment]
I've implemented this with a different property value, "rootfs", because receiving into the root of a pool will destroy any filesystems which aren't in the source.  If you want this, set the property explicitly.
